name: Development build

on: workflow_dispatch

jobs:
  connection-test:
    name: Test VPS connection
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote command on vps
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEVELOPMENT_HOST }}
          username: ${{ secrets.DEVELOPMENT_USERNAME }}
          password: ${{ secrets.DEVELOPMENT_PASSWORD }}
          script: pwd

  project-build:
    name: Build project
    needs: connection-test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Fetch LFS assets
        run: git lfs checkout

      - name: Use Node.js 15.8.0
        uses: actions/setup-node@v2-beta
        with:
          node-version: "15.8.0"

      - name: Building website
        run: |
          yarn
          yarn build
